### ISSUE TITLE
Edit Team Cards

### ISSUE THREAD

**Issue by KartikeyCode** [Blockchain-Club-SRM/blockchainsrm.org-v2#37]
. Remove the background image of the cards.
. make the main profile picture larger.
. add separate buttons for social media links. ( 3 buttons -> linkedin, twitter and github respectively)
. load the cards dynamically (use a .map() on it ) (add lazy loading too) 

![image](https://github.com/Blockchain-Club-SRM/blockchainsrm.org-v2/assets/110187856/9f950a98-0ca8-4b0e-aea0-e04d743af040)

**Comment by karanpargal** [comment]
Already pushed on main. 

Closing this issue.

Resolved by @karanpargal by commit hash b8d8a44
