### ISSUE TITLE
Add Hackathon and Event Images

### ISSUE THREAD

**Issue by ahaan1984** [Blockchain-Club-SRM/blockchainsrm.org-v2#44]
Update the Events section by adding Hackathons and Events Images as a slider frame.

![image](https://github.com/Blockchain-Club-SRM/blockchainsrm.org-v2/assets/113466054/d19a4230-7a30-4c5e-aec2-70d5439ca584)

**Comment by KartikeyCode** [comment]
Starting work on the issue
