### ISSUE TITLE
Update team page

### ISSUE THREAD

**Issue by MajorTimberWolf** [Blockchain-Club-SRM/blockchainsrm.org-v2#60]
**Update the team name with the list of new recruits plus removing old members. Update the page with images and proper links.** 

Will add response sheet for the names here soon: https://drive.google.com/drive/folders/15kYHqCTmUWjHajsC4TQlKV-IyoHn0BPVUrhpiGzdCSjCrhgTR5sMCQjH2fmSSCLGhuI4ST5r

**Comment by PaleDeath** [comment]
Closed
